"""create initial schema

Revision ID: e1a2c4340b1c
Revises:
Create Date: 2026-08-21 13:23:44.929905

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e1a2c4340b1c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_users")),
        sa.UniqueConstraint("email", name=op.f("uq_admin_users_email")),
    )
    op.create_table(
        "channels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_channels")),
        sa.UniqueConstraint("name", name=op.f("uq_channels_name")),
        sa.UniqueConstraint("slug", name=op.f("uq_channels_slug")),
    )
    op.create_table(
        "clubs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("short_name", sa.String(length=80), nullable=False),
        sa.Column("crest_path", sa.String(length=255), nullable=True),
        sa.Column("is_tracked", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clubs")),
        sa.UniqueConstraint("name", name=op.f("uq_clubs_name")),
        sa.UniqueConstraint("slug", name=op.f("uq_clubs_slug")),
    )
    op.create_index(op.f("ix_clubs_is_active"), "clubs", ["is_active"], unique=False)
    op.create_index(op.f("ix_clubs_is_tracked"), "clubs", ["is_tracked"], unique=False)
    op.create_table(
        "competitions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competitions")),
        sa.UniqueConstraint("name", name=op.f("uq_competitions_name")),
        sa.UniqueConstraint("slug", name=op.f("uq_competitions_slug")),
    )
    op.create_table(
        "leagues",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("tier", sa.SmallInteger(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("tier > 0", name=op.f("ck_leagues_positive_tier")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leagues")),
        sa.UniqueConstraint("name", name=op.f("uq_leagues_name")),
        sa.UniqueConstraint("slug", name=op.f("uq_leagues_slug")),
    )
    op.create_table(
        "normalisation_cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("context", sa.String(length=32), nullable=False),
        sa.Column("raw_value", sa.String(length=255), nullable=False),
        sa.Column("lookup_key", sa.String(length=255), nullable=False),
        sa.Column("normalized_value", sa.String(length=255), nullable=False),
        sa.Column("resolution_method", sa.String(length=32), nullable=False),
        sa.Column("provider_key", sa.String(length=80), nullable=True),
        sa.Column("model_name", sa.String(length=120), nullable=True),
        sa.Column("needs_review", sa.Boolean(), nullable=False),
        sa.Column("use_count", sa.Integer(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "context IN ('club', 'competition', 'channel')",
            name=op.f("ck_normalisation_cache_valid_context"),
        ),
        sa.CheckConstraint(
            "resolution_method IN ('rule', 'alias', 'manual', 'groq')",
            name=op.f("ck_normalisation_cache_valid_resolution_method"),
        ),
        sa.CheckConstraint(
            "use_count >= 0", name=op.f("ck_normalisation_cache_non_negative_use_count")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_normalisation_cache")),
        sa.UniqueConstraint("context", "lookup_key", name="uq_normalisation_cache_context_lookup"),
    )
    op.create_table(
        "scrape_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trigger", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sources_attempted", sa.Integer(), nullable=False),
        sa.Column("sources_successful", sa.Integer(), nullable=False),
        sa.Column("matches_found", sa.Integer(), nullable=False),
        sa.Column("matches_created", sa.Integer(), nullable=False),
        sa.Column("matches_updated", sa.Integer(), nullable=False),
        sa.Column("unknown_terms", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('running', 'completed', 'partial', 'failed')",
            name=op.f("ck_scrape_runs_valid_status"),
        ),
        sa.CheckConstraint(
            "trigger IN ('scheduled', 'manual')", name=op.f("ck_scrape_runs_valid_trigger")
        ),
        sa.CheckConstraint(
            "sources_attempted >= 0 AND sources_successful >= 0 AND matches_found >= 0 AND matches_created >= 0 AND matches_updated >= 0 AND unknown_terms >= 0 AND error_count >= 0",
            name=op.f("ck_scrape_runs_non_negative_counters"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scrape_runs")),
    )
    op.create_table(
        "club_aliases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("club_id", sa.Integer(), nullable=False),
        sa.Column("alias", sa.String(length=160), nullable=False),
        sa.Column("normalized_alias", sa.String(length=160), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["club_id"],
            ["clubs.id"],
            name=op.f("fk_club_aliases_club_id_clubs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_club_aliases")),
        sa.UniqueConstraint("normalized_alias", name="uq_club_aliases_normalized_alias"),
    )
    op.create_table(
        "club_source_mappings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("club_id", sa.Integer(), nullable=False),
        sa.Column("provider_key", sa.String(length=80), nullable=False),
        sa.Column("source_slug", sa.String(length=255), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["club_id"],
            ["clubs.id"],
            name=op.f("fk_club_source_mappings_club_id_clubs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_club_source_mappings")),
        sa.UniqueConstraint(
            "club_id", "provider_key", name="uq_club_source_mappings_club_provider"
        ),
    )
    op.create_table(
        "league_memberships",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("club_id", sa.Integer(), nullable=False),
        sa.Column("league_id", sa.Integer(), nullable=False),
        sa.Column("season", sa.String(length=9), nullable=False),
        sa.Column("display_order", sa.SmallInteger(), nullable=False),
        sa.Column("is_confirmed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "display_order > 0", name=op.f("ck_league_memberships_positive_display_order")
        ),
        sa.ForeignKeyConstraint(
            ["club_id"],
            ["clubs.id"],
            name=op.f("fk_league_memberships_club_id_clubs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["league_id"],
            ["leagues.id"],
            name=op.f("fk_league_memberships_league_id_leagues"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_league_memberships")),
        sa.UniqueConstraint("club_id", "season", name="uq_league_memberships_club_season"),
    )
    op.create_index(
        "ix_league_memberships_league_season_order",
        "league_memberships",
        ["league_id", "season", "display_order"],
        unique=False,
    )
    op.create_table(
        "matches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("kickoff_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("home_club_id", sa.Integer(), nullable=True),
        sa.Column("away_club_id", sa.Integer(), nullable=True),
        sa.Column("home_name_raw", sa.String(length=160), nullable=False),
        sa.Column("away_name_raw", sa.String(length=160), nullable=False),
        sa.Column("home_name_display", sa.String(length=160), nullable=False),
        sa.Column("away_name_display", sa.String(length=160), nullable=False),
        sa.Column("competition_id", sa.Integer(), nullable=False),
        sa.Column("provider_key", sa.String(length=80), nullable=False),
        sa.Column("source_status", sa.String(length=40), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_stale", sa.Boolean(), nullable=False),
        sa.Column("needs_review", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "home_club_id IS NULL OR away_club_id IS NULL OR home_club_id <> away_club_id",
            name=op.f("ck_matches_different_home_and_away_clubs"),
        ),
        sa.ForeignKeyConstraint(
            ["away_club_id"],
            ["clubs.id"],
            name=op.f("fk_matches_away_club_id_clubs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competitions.id"],
            name=op.f("fk_matches_competition_id_competitions"),
        ),
        sa.ForeignKeyConstraint(
            ["home_club_id"],
            ["clubs.id"],
            name=op.f("fk_matches_home_club_id_clubs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_matches")),
        sa.UniqueConstraint("fingerprint", name=op.f("uq_matches_fingerprint")),
    )
    op.create_index(op.f("ix_matches_kickoff_at"), "matches", ["kickoff_at"], unique=False)
    op.create_index("ix_matches_kickoff_stale", "matches", ["kickoff_at", "is_stale"], unique=False)
    op.create_table(
        "scrape_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("requested_by_admin_id", sa.Integer(), nullable=True),
        sa.Column("run_id", sa.Integer(), nullable=True),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'completed', 'failed')",
            name=op.f("ck_scrape_jobs_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_admin_id"],
            ["admin_users.id"],
            name=op.f("fk_scrape_jobs_requested_by_admin_id_admin_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["scrape_runs.id"],
            name=op.f("fk_scrape_jobs_run_id_scrape_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scrape_jobs")),
    )
    op.create_table(
        "scrape_run_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("stage", sa.String(length=80), nullable=False),
        sa.Column("source_reference", sa.String(length=255), nullable=True),
        sa.Column("level", sa.String(length=20), nullable=False),
        sa.Column("error_type", sa.String(length=120), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "level IN ('info', 'warning', 'error')", name=op.f("ck_scrape_run_events_valid_level")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["scrape_runs.id"],
            name=op.f("fk_scrape_run_events_run_id_scrape_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scrape_run_events")),
    )
    op.create_table(
        "match_channels",
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channels.id"],
            name=op.f("fk_match_channels_channel_id_channels"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
            name=op.f("fk_match_channels_match_id_matches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("match_id", "channel_id", name=op.f("pk_match_channels")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("match_channels")
    op.drop_table("scrape_run_events")
    op.drop_table("scrape_jobs")
    op.drop_index("ix_matches_kickoff_stale", table_name="matches")
    op.drop_index(op.f("ix_matches_kickoff_at"), table_name="matches")
    op.drop_table("matches")
    op.drop_index("ix_league_memberships_league_season_order", table_name="league_memberships")
    op.drop_table("league_memberships")
    op.drop_table("club_source_mappings")
    op.drop_table("club_aliases")
    op.drop_table("scrape_runs")
    op.drop_table("normalisation_cache")
    op.drop_table("leagues")
    op.drop_table("competitions")
    op.drop_index(op.f("ix_clubs_is_tracked"), table_name="clubs")
    op.drop_index(op.f("ix_clubs_is_active"), table_name="clubs")
    op.drop_table("clubs")
    op.drop_table("channels")
    op.drop_table("admin_users")
    # ### end Alembic commands ###
